### ISSUE TITLE
Lab9

### ISSUE THREAD

**Issue by tharanieraj** [vivekanandas/csc532#2]
In Lab9 

This page is to create a form to allow the user to enter some data. When any character is entered in the input field, nothing happens. When the Enter key is pressed in the input field, alert saying that the ### **Enter is pressed in the text box**. (Not displaying these exact words) **When the Enter key is pressed outside the input field, i.e. in the body, alert saying that the Enter is pressed in somewhere.** (This is totally missing!!)

**Comment by vivekanandas** [comment]
@tharanieraj 
Done. Next time when you create an issue please make sure to assign it to me otherwise I will not get notification.

**Comment by tharanieraj** [comment]
Sure, I didn't know that before. Will do it next time :) And it's all working. Submitted already.Thanks!
